# 第2章 集めたデータは前処理が必要

## 05 表データを読み込もう

### データフレームを作る

リスト2.1

In [1]:
import pandas as pd
data = [
    [60,65,66],
    [80,85,88],
    [100,100,100]
]
df = pd.DataFrame(data)
df

     0    1    2
0   60   65   66
1   80   85   88
2  100  100  100

リスト2.2

In [2]:
df.columns=["国語","数学","英語"]
df.index=["A太","B介","C子"]
df

     国語   数学   英語
A太   60   65   66
B介   80   85   88
C子  100  100  100

リスト 2.3

In [4]:
import pandas as pd
data = [
    [60,65,66],
    [80,85,88],
    [100,100,100]
]
col = ["国語","数学","英語"]
idx =  ["A太","B介","C子"]
df = pd.DataFrame(data, columns=col, index=idx)
df

     国語   数学   英語
A太   60   65   66
B介   80   85   88
C子  100  100  100

リスト2.4

In [5]:
import pandas as pd
data = {
    "国語" : [60,80,100],
    "数学" : [65,85,100],
    "英語" : [66,88,100]
}
idx =  ["A太","B介","C子"]
df = pd.DataFrame(data, index=idx)
df

     国語   数学   英語
A太   60   65   66
B介   80   85   88
C子  100  100  100

### データファイルを読み込む

リスト2.5

In [6]:
import pandas as pd
df = pd.read_csv("test.csv")
df

   名前   国語  数学  英語  学生番号
0  A太   83  89  76  A001
1  B介   66  93  75  B001
2  C子  100  84  96  B002
3  D郎   60  73  40  A002
4  E美   92  62  84  C001
5  F菜   96  92  94  C002

リスト2.6

In [7]:
import pandas as pd
df = pd.read_csv("testSJIS.csv", encoding="Shift_JIS")
df

   名前   国語  数学  英語  学生番号
0  A太   83  89  76  A001
1  B介   66  93  75  B001
2  C子  100  84  96  B002
3  D郎   60  73  40  A002
4  E美   92  62  84  C001
5  F菜   96  92  94  C002

リスト2.7

In [8]:
import pandas as pd
df = pd.read_csv("test.csv", index_col=0)
df

     国語  数学  英語  学生番号
名前
A太   83  89  76  A001
B介   66  93  75  B001
C子  100  84  96  B002
D郎   60  73  40  A002
E美   92  62  84  C001
F菜   96  92  94  C002

リスト2.8

In [10]:
import pandas as pd
df = pd.read_csv("testNoHeader.csv", index_col=0, header=None)
df

      1   2   3     4
0
A太   83  89  76  A001
B介   66  93  75  B001
C子  100  84  96  B002
D郎   60  73  40  A002
E美   92  62  84  C001
F菜   96  92  94  C002

## 06 データをざっくりと眺める

### データを眺める

リスト2.9

In [11]:
import pandas as pd
df = pd.read_csv("test.csv", index_col=0)
df.head()

     国語  数学  英語  学生番号
名前
A太   83  89  76  A001
B介   66  93  75  B001
C子  100  84  96  B002
D郎   60  73  40  A002
E美   92  62  84  C001

リスト2.10

In [9]:
df.columns

Index(['国語', '数学', '英語', '学生番号'], dtype='object')

リスト2.11

In [10]:
df.index

Index(['A太', 'B介', 'C子', 'D郎', 'E美', 'F菜'], dtype='object', name='名前')

リスト2.12

In [11]:
# 列名をリストに変換する
list1 = [i for i in df.columns]
print(list1)

# インデックス名をリストに変換する
list2 = [i for i in df.index]
print(list2)

['国語', '数学', '英語', '学生番号']
['A太', 'B介', 'C子', 'D郎', 'E美', 'F菜']

リスト2.13

In [12]:
df.dtypes

国語       int64
数学       int64
英語       int64
学生番号    object
dtype: object

リスト2.14

In [16]:
len(df)

6

### 列データを取り出す

リスト2.15

In [13]:
df["国語"]

名前
A太     83
B介     66
C子    100
D郎     60
E美     92
F菜     96
Name: 国語, dtype: int64

リスト2.16

In [14]:
df[["国語","数学"]]

     国語  数学
名前
A太   83  89
B介   66  93
C子  100  84
D郎   60  73
E美   92  62
F菜   96  92

### 行データを取り出す

リスト2.17

In [15]:
df.iloc[0]

国語        83
数学        89
英語        76
学生番号    A001
Name: A太, dtype: object

リスト2.18

In [20]:
df.iloc[[0,3]]

    国語  数学  英語  学生番号
名前
A太  83  89  76  A001
D郎  60  73  40  A002

## 要素データを取り出す

リスト2.19

In [23]:
df.iloc[0]["国語"]

83

## 07 データのどこを使う？

### 列データや行データを追加する

リスト2.20

In [24]:
import pandas as pd
dfA = pd.read_csv("test.csv", index_col=0)

dfB = pd.DataFrame()
dfB["国語"] = dfA["国語"]
dfB

     国語
名前
A太   83
B介   66
C子  100
D郎   60
E美   92
F菜   96

リスト2.21

In [25]:
dfA = pd.read_csv("test.csv", index_col=0)

dfB = pd.DataFrame()
dfB = pd.concat([dfB, pd.DataFrame(dfA.iloc[0]).T])
dfB

    国語  数学  英語  学生番号
A太  83  89  76  A001

### 列データや行データを削除する

リスト2.22

In [30]:
dfA = pd.read_csv("test.csv", index_col=0)
dfA = dfA.drop("国語", axis=1)
dfA

    数学  英語  学生番号
名前
A太  89  76  A001
B介  93  75  B001
C子  84  96  B002
D郎  73  40  A002
E美  62  84  C001
F菜  92  94  C002

リスト2.23

In [27]:
dfA = pd.read_csv("test.csv", index_col=0)
dfA = dfA.drop(dfA.index[3])
dfA

     国語  数学  英語  学生番号
名前
A太   83  89  76  A001
B介   66  93  75  B001
C子  100  84  96  B002
E美   92  62  84  C001
F菜   96  92  94  C002

### 条件でデータを抽出する

リスト2.24

In [ ]:
import pandas as pd
dfA = pd.read_csv("test.csv", index_col=0)
dfA["国語"] > 80

名前
A太     True
B介    False
C子     True
D郎    False
E美     True
F菜     True
Name: 国語, dtype: bool

リスト2.25

In [ ]:
dfB = dfA[dfA["国語"] > 80]
dfB

     国語  数学  英語  学生番号
名前
A太   83  89  76  A001
C子  100  84  96  B002
E美   92  62  84  C001
F菜   96  92  94  C002

リスト2.26

In [ ]:
dfB = dfA[(dfA["国語"] > 80) & (dfA["数学"] > 80)]
dfB

     国語  数学  英語  学生番号
名前
A太   83  89  76  A001
C子  100  84  96  B002
F菜   96  92  94  C002

## 08 データのミスをチェックする：欠損値

### 欠損値の処理

リスト2.27

In [30]:
import pandas as pd
data = {
    "国語" : [90,50,None,40],
    "数学" : [80,None,None,50]
}
idx =  ["A太","B介","C子","D郎"]
dfA = pd.DataFrame(data, index=idx)
dfA

      国語    数学
A太  90.0  80.0
B介  50.0   NaN
C子   NaN   NaN
D郎  40.0  50.0

リスト2.28

In [31]:
dfA.isnull().sum()

国語    1
数学    2
dtype: int64

リスト2.29

In [32]:
dfB = dfA.dropna()
dfB

      国語    数学
A太  90.0  80.0
D郎  40.0  50.0

リスト2.30

In [33]:
dfB = dfA.dropna(subset=["国語"])
dfB

      国語    数学
A太  90.0  80.0
B介  50.0   NaN
D郎  40.0  50.0

リスト2.31

In [23]:
dfB = dfA.fillna(dfA.mean())
dfB

      国語    数学
A太  90.0  80.0
B介  50.0  65.0
C子  60.0  65.0
D郎  40.0  50.0

リスト2.32

In [34]:
dfB = dfA.fillna(method='ffill')
dfB

C:\Users\satos\AppData\Local\Temp\ipykernel_25204\1780552846.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfB = dfA.fillna(method='ffill')

      国語    数学
A太  90.0  80.0
B介  50.0  80.0
C子  50.0  80.0
D郎  40.0  50.0

## 重複したデータを削除する

リスト2.33

In [28]:
import pandas as pd
data = [
    [10,30,40],
    [20,30,40],
    [20,30,40],
    [30,30,50],
    [20,30,40]
        ]
dfA = pd.DataFrame(data)
dfA

    0   1   2
0  10  30  40
1  20  30  40
2  20  30  40
3  30  30  50
4  20  30  40

リスト2.34

In [35]:
dfA.duplicated().value_counts()

False    4
Name: count, dtype: int64

リスト2.35

In [36]:
dfB = dfA.drop_duplicates()
dfB

      国語    数学
A太  90.0  80.0
B介  50.0   NaN
C子   NaN   NaN
D郎  40.0  50.0

### 文字列型のデータを数値に変換する

リスト2.36

In [41]:
import pandas as pd
data = {
    "A" : ["100","300"],
    "B" : ["500","1,500"]
}
dfA = pd.DataFrame(data)
dfA

     A      B
0  100    500
1  300  1,500

リスト2.37

In [37]:
dfA.dtypes

国語    float64
数学    float64
dtype: object

リスト2.38

In [42]:
dfA["A"] = dfA["A"].astype(int)
dfA.dtypes

A     int32
B    object
dtype: object

リスト2.39

In [43]:
dfA["B"] = dfA["B"].str.replace(",","").astype(int)
dfA.dtypes

A    int32
B    int32
dtype: object

リスト2.40

In [44]:
dfA

     A     B
0  100   500
1  300  1500